services:
  user_api:
    container_name: "user_api"
    build:
      context: .
      dockerfile: ./authUser/Dockerfile
    ports:
      - "80:8080"
    environment:
      FIREBASE_KEY: ${FIREBASE_KEY}
      FIREBASE_URL: ${FIREBASE_URL}